### ISSUE TITLE
Creeper Issue

### ISSUE THREAD

**Issue by m853ax** [BillyGalbreath/Ridables#31] opened 2019-01-16 18:29 UTC
The creepers doesn't explode

**Comment by BillyGalbreath** [comment] 2019-01-19 03:02
Cannot reproduce.

**Comment by mikroskeem** [comment] 2019-03-01 17:25
But I can!

```
[17:46:42 WARN]: Entity threw exception at world:1280.7484039867722,72.0,690.7280864643808
[17:46:42 WARN]: java.lang.NoSuchFieldError: aX
[17:46:42 WARN]: at net.pl3x.bukkit.ridables.entity.RidableCreeper.explode(RidableCreeper.java:260)
[17:46:42 WARN]: at net.pl3x.bukkit.ridables.entity.RidableCreeper.tick(RidableCreeper.java:120)
[17:46:42 WARN]: at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1556)
[17:46:42 WARN]: at net.minecraft.server.v1_13_R2.World.g(World.java:1523)
[17:46:42 WARN]: at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1330)
[17:46:42 WARN]: at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598)
[17:46:42 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1099)
[17:46:42 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[17:46:42 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[17:46:42 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[17:46:42 WARN]: at java.lang.Thread.run(Thread.java:748) 
```

**Comment by BillyGalbreath** [comment] 2019-03-22 01:19
I'm closing this because its not a problem with the plugin. Blame md_5 for all the [mid-version NMS remappings](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/builddata/commits). v2.x is stuck in the past, pre his remappings.

Update to [v3.0 and Paper build 568+](https://papermc.io/forums/t/1-13-2-ridables-ride-and-control-any-mob-with-full-wasd-controls/102)

**Closed as completed by BillyGalbreath** 2019-03-22 01:19 UTC
