### ISSUE TITLE
Won't be able to dismount

### ISSUE THREAD

**Issue by x1p** [BillyGalbreath/Ridables#26] opened 2018-11-21 11:44 UTC
Tried Ridables, not that I need it. I tried to let fish spawn since the fish bug which doesn't even work with the Mojangs ocean_reviver.

Enabled the squid as an example.
Opped myself
Left click to ride
Left shift won't dismount
Only using /spawn dismounts it. Even /tppos does not help, I can't teleport.

Tried Ridables build 54 from the jenkins
Tried Ridables 2.5.6 from the spigot
Latest Paper

**Comment by BillyGalbreath** [comment] 2018-11-21 13:15
Could you elaborate a bit? What fish bug? What is ocean reviver? Etc..

Does this happen for you with no other plugins installed? If not, which
plugin breaks it?

**Comment by x1p** [comment] 2018-11-21 15:09
I'm speaking about this bug:
https://bugs.mojang.com/browse/MC-134702
This prevents fish spawn around the world if a fish tank is build on the spawn.

Anyway. They do spawn with ridables installed.
I'll try to eliminate other plugins

**Comment by BillyGalbreath** [comment] 2018-11-21 15:20
That bug was fixed in vanilla 1.13.2, but md_5 broke it again in
CraftBukkit.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/EntityFish.patch

v2 of Ridables doesn't fix this itself because it wasn't a problem before
md_5 messed with the logic. However, in the upcoming v3 of Ridables this is
fixed.

https://github.com/BillyGalbreath/Ridables/blob/v3.0/src/main/java/net/pl3x/bukkit/ridables/entity/animal/fish/RidableCod.java#L53-L63

As for the dismount issue, @electronicboy has been trying some changes
around the logic in Paper to hopefully fix some inconsistencies (or
something). Try using build 456 (no idea if that's your already using or
not). If the problem still persists try downgrading to build 446 (447 was
the first build with the dismount code changes and is known to cause
issues).

If the problem still persists on build 446 then you have a conflicting
plugin doing something weird.

**Comment by x1p** [comment] 2018-11-21 15:38
I tested it with paper build 456.
I suspected CMI. It has something like this too. Tried unloading it, but didn't help.

I don't really need Ridables and have a lack of time. So i won't go any further for now.

**Comment by BillyGalbreath** [comment] 2018-11-22 00:03
Ok. Going to close this then. No one else is reporting that issue, and it definitely works as intended. So idk what to tell you.

**Closed as completed by BillyGalbreath** 2018-11-22 00:03 UTC
Labels: invalid
