### ISSUE TITLE
Request: Block riding mobs in protected regions

### ISSUE THREAD

**Issue by ghost** [BillyGalbreath/Ridables#22] opened 2018-10-23 04:18 UTC
A feature to block players from riding mobs in protected regions i.e. spawn; Can be enabled or disabled in the config.

**Comment by BillyGalbreath** [comment] 2018-10-23 05:34
Does the `ride` region flag not work? I've never actually thought of or tested that.

**Comment by ghost** [comment] 2018-10-23 10:36
The ride flag does not work.

**Comment by BillyGalbreath** [comment] 2018-10-23 11:46
Ok, I'll look at WorldGuard sometime this weekend and find out why that flag isn't working. It may just be listening to the vehicle events, which doesn't cover all entities. Maybe @me4502 knows off the top his head and can confirm.

**Comment by ghost** [comment] 2018-10-24 06:04
Yes, players can also bypass no entry regions when they're on the dolphin as well, which can get quite aggravating. Had a couple regular players bounce their way in a donor club with protected entry, but of course they bypassed it due to them riding the dolphin.

**Comment by BillyGalbreath** [comment] 2018-10-24 06:44
The entry flag is a bug in WorldGuard's implementation. I have seen that before, and I am able to recreate it on a vanilla horse. Sometimes the player will get stuck in a glitch, other times the horse starts flying straight up, and other times (rarer than the others) it will let the player enter the region. That's something WG will have to fix, if they want it fixed.

I'm pretty sure the ride flag is another thing WG itself can fix. Not sure if it's a bug in the implementation, or just an oversight. Probably the latter.

As for fixing these inside Ridables, this is definitely possible, but it will introduce lag to the plugin having to scan for locations and regions all the time. Lag is one of my top concerns with this plugin because the entities themselves are already laggy before I even get my code on  them. If something can be fixed elsewhere without adding to the lag, I'm in favor of that option.

**Comment by ghost** [comment] 2018-10-24 06:56
I completely agree, do you suggest any methods I can use to stop players from entering the donor region?

**Comment by BillyGalbreath** [comment] 2018-10-24 07:26
I could write you a small plugin that will eject a player from riding any entity when they try to enter a region they can't. It won't be tied to Ridables at all, but will work with those entities.

While I'm at it I can extend the `ride` flag's behavior to include any entity, not just vehicles. It should then behave as you expect.

Got any suggested names for that plugin?

**Comment by ghost** [comment] 2018-10-24 07:57
Would that cause lag for my server? And if not, sounds like a plan! The name could be something like EntityDeny. You can message me on Discord my user is Kalasky#0001

**Comment by BillyGalbreath** [comment] 2018-10-24 09:44
Not gonna lie, it might. I mean, I don't think it will but there's always that chance. Won't know until we try.

When my work week finishes I'll get Ridables updated to 1.13.2, and then I'll work on this side plugin (shouldn't take but a few minutes to write). ;)

**Comment by ghost** [comment] 2018-10-24 12:44
Alrighty sounds like a plan.

**Comment by me4502** [comment] 2018-10-25 04:32
When I get a chance I'll have a look at the entry flag issue. Is the `ride` flag a flag inside WorldGuard? If so I'll have a look at that one as well.

**Comment by ghost** [comment] 2018-10-25 12:29
Yes it's inside of WorldGuard.

**Comment by ghost** [comment] 2018-10-28 01:09
Any news on the plugin?

**Comment by BillyGalbreath** [comment] 2018-10-28 22:54
> Any news on the plugin?

Sorry for late reply @Kalasky. Got tied up with motorcycle for a bit ^_^

Ok, so. I started to write the plugin, but a bigger issue appeared. Turns out the `PlayerMoveEvent` is not firing for the ridable mobs in my plugin. This is why protection plugins let them move around freely, because they use that event to check if a player has permission to enter.

I am currently working on a fix for this event (I think i'm onto something here), but the glitchy issues with WorldGuard will still remain. So after I fix Ridables to fire the appropriate events, I'll still make the extra plugin to fix WorldGuard's glitchy enter/exit flags.

Also, Idk how I'm going to handle the `ride` flag because WorldGuard actually creates a cyclic issue where I cant eject the player because it cancels that with a message of "Can't disembark here" yadda yadda. So the player gets stuck (cant mount or dismount) and you get the glitchyness all over again. So I'll probably leave this `ride` flag alone.

**Comment by BillyGalbreath** [comment] 2018-10-29 01:11
Ok, I made a new release, v2.56, which fires the PlayerMoveEvent when moving while riding a mob. This fixes the original issue reported here about WorldGuard's `entry` flag not working. But there are still other issues beyond my control about how WorldGuard handles ejecting players from Vehicles (horse, llama, pig, etc) which @me4502 will have to fix in WorldGuard.

I did not make a separate plugin after all, because it simply wasn't needed and it would not fix the glitchiness issues. Just download v2.56 and enable the new `enable-entity-move-event` option on config.yml (you will have to manually add it yourself, or delete your config and let it rebuild a new one).

@me4502 I pinpointed the cause of the glitchiness to cancelling the VehicleExitEvent. WorldGuard ejects players when they cross into a region with the `entry` flag set to deny, but the VehicleExitEvent cancels this because "Don't disembark here! You can't get back on." ;)

@Kalasky I'll leave this ticket open until you can verify the original issue is fixed for you :)

**Comment by ghost** [comment] 2018-10-30 17:08
Works like a charm thank you very much!

**Closed as completed** 2018-10-30 22:15 UTC
