### ISSUE TITLE
My server crashes...

### ISSUE THREAD

**Issue by TheIntelloBox** [BillyGalbreath/Ridables#28] opened 2018-12-27 13:17 UTC
[14:16:23] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 
	at net.pl3x.bukkit.ridables.entity.RidableEnderman.n(RidableEnderman.java:219) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityInsentient.<init>(EntityInsentient.java:70) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityCreature.<init>(EntityCreature.java:15) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityMonster.<init>(EntityMonster.java:7) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityEnderman.<init>(EntityEnderman.java:21) ~[patched_1.13.2.jar:git-Paper-488]
	at net.pl3x.bukkit.ridables.entity.RidableEnderman.<init>(RidableEnderman.java:49) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:275) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:299) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:280) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:286) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:1124) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:1064) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:1088) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:809) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.postChunk(PaperAsyncChunkProvider.java:518) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:116) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:110) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:105) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:98) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchMethodError: 
	... 24 more
[14:16:23] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoSuchMethodError: 
	at net.pl3x.bukkit.ridables.entity.RidableEnderman.n(RidableEnderman.java:219) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityInsentient.<init>(EntityInsentient.java:70) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityCreature.<init>(EntityCreature.java:15) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityMonster.<init>(EntityMonster.java:7) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityEnderman.<init>(EntityEnderman.java:21) ~[patched_1.13.2.jar:git-Paper-488]
	at net.pl3x.bukkit.ridables.entity.RidableEnderman.<init>(RidableEnderman.java:49) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:275) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:299) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:280) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityTypes.a(EntityTypes.java:286) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:1124) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:1064) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.a(ChunkRegionLoader.java:1088) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:809) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.postChunk(PaperAsyncChunkProvider.java:518) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:116) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:110) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:105) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:98) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by smmmadden** [comment] 2018-12-27 13:51
you need to set the enderman ridable to "false".  It's because Billy hasn't had time to build the plugin on the latest code yet. :-)  You might get one for pigs as well, but that one isn't crashing my server.

**Comment by smmmadden** [comment] 2019-01-01 18:39
@BillyGalbreath - this also throws exceptions with the pigs too.  You don't need to be on one, but just being near one with throw a similar exception.  I'm on PaperSpigot 488, so not sure if Paper broke something or just a compiling issue that needs to be updated on your end.  It does get very noisy in the logs with many players.

**Comment by BillyGalbreath** [comment] 2019-01-02 06:42
This happens because md_5 remapped nms mid version lifecycle. He was supposed to do something like this between major version releases (aka, when 1.14 releases).

I will have to update the plug-in to the new mappings for it to work.

Temporary solution is to downgrade your server to the last known working version (before the big nms remapping).

**Comment by BillyGalbreath** [comment] 2019-01-02 06:42
Duplicate of #27

**Closed as completed by BillyGalbreath** 2019-01-02 06:42 UTC

**Comment by smmmadden** [comment] 2019-01-02 13:49
Thanks Billy, downgraded to 481 and all is working again.  Happy New Years! :-)

**Comment by AJ552** [comment] 2019-01-18 23:33
> Thanks Billy, downgraded to 481 and all is working again. Happy New Years! :-)

smmmadden can u tell me how to downgrade my spigot version to the 481 version?
thank you in anticipate!

**Comment by smmmadden** [comment] 2019-01-19 02:56
Hi @AJ552 - I'm currently running on PaperSpigot build 500 but will be upgrading later this weekend to whatever the now current build is.  You can upgrade as well, but you will need to disable Enderman and Pig riding.  Then you'll see some warnings if you move too fast or fly around but they'll go away as well.  Until @BillyGalbreath can rebuild the plugin on the latest build or remove the dependency to a specific build, this is what I'd recommend doing.  Otherwise, reporting bugs on 481 and trying to get them fixed will be slim to none as it's too old.  Sucks to have to trade off one for the other, but this does work. :-)

**Comment by BillyGalbreath** [comment] 2019-01-19 03:01
v3.0-BETA1 fixes this (released on Discord) ;)

**Comment by smmmadden** [comment] 2019-01-19 03:14
AWESOME!!  Thank you sir!  Stay warm this weekend. :-)
