### ISSUE TITLE
consolenerror

### ISSUE THREAD

**Issue by hajudahim** [BillyGalbreath/Ridables#41] opened 2019-03-28 12:26 UTC
[13:08:43 ERROR]: net/minecraft/server/v1_13_R2/BlockPosition$b initializing Ridables v2.56 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$b
        at net.pl3x.bukkit.ridables.entity.RidableType.<clinit>(RidableType.java:54) ~[?:?]
        at net.pl3x.bukkit.ridables.Ridables.onLoad(Ridables.java:73) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:330) [spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$b
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 6 more

**Comment by BillyGalbreath** [comment] 2019-03-28 13:06
Duplicate of #30

Downgrade your Spigot server, or Upgrade to Paper 568+ and Ridables v3.0

**Closed as completed by BillyGalbreath** 2019-03-28 13:06 UTC
